app/app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('users.urls', namespace='user')),
    path('exam/', include('exam.urls', namespace='exam')),


]

app/exam/urls.py
# from django.contrib import admin
from django.urls import path, include

from exam import views

app_name = 'exam'

urlpatterns = [
    path('', views.ExamView.as_view(), name='exam'),
    path('add/', views.AddInternView.as_view(), name='add_intern'),
    path('CheckList/', views.CheckListView.as_view(), name='CheckList'),
    path('edit/<int:pk>', views.ExamUpdateView.as_view(), name='edit_intern'),

]

app/main/urls.py
# from django.contrib import admin
from django.urls import path, include

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('main', views.index_main, name='index_main'),
    path('about/', views.about, name='about'),
    path('dm/', views.dm, name='dm'),
    path('cc_1/', views.cc_1, name='cc_1'),
    path('cc_2/', views.cc_2, name='cc_2'),

]

app/users/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

app/main/models.py
from django.db import models

# Create your models here.

app/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from users.models import User


@login_required
def index(request):
    company = request.user.company
    # list_person = User.objects.filter(company__startswith='cc')
    list_person = User.objects.all()
    context = {
        'title': 'Главная',
        'content': 'Главная страница',
        'company': company,
        'id': company,
        'list_person': list_person,
    }
    return render(request, 'main/index.html', context)


@login_required
def index_main(request):
    company = request.user.company
    # list_person = User.objects.filter(company__startswith='cc')
    list_person = User.objects.all()
    context = {
        'title': 'Главная',
        'content': 'Главная страница',
        'company': company,
        'list_person': list_person,
    }
    return render(request, 'main/index_main.html', context)


@login_required
def about(request):
    company = request.user.company
    context = {
        'title': 'About',
        'content': 'About-Page',
        'company': company,
    }
    return render(request, 'main/about.html', context)


@login_required
def dm(request):
    context = {
        'title': 'DM',
        'content': 'DM',
    }
    return render(request, 'main/dm.html', context)


@login_required
def cc_1(request):
    context = {
        'title': 'CC_1',
        'content': 'CC_1',
    }
    return render(request, 'main/cc_1.html', context)


@login_required
def cc_2(request):
    context = {
        'title': 'CC_2',
        'content': 'CC_2',
    }
    return render(request, 'main/cc_2.html', context)

app/main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div class="users">
        <h1>
            {{ content }}
        </h1>
    </div>
{% endblock %}

app/main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "deps/css/test.css" %}">
</head>
<body>
<div>
    <nav class="header">
        <div class="menu">
            <a href="{% url "main:index" %}">Главная</a>
            <a href="{% url "main:index_main" %}">main</a>
            <a href="{% url "main:about" %}">О нас</a>

                <a href="{% url "admin:index" %}">Админ-панель</a>

            <a href="{% url "exam:exam"%}">Зачеты</a>
        </div>
        <div class="menu">
            <a href="{% url "users:logout" %}">Выйти</a>
        </div>

    </nav>
</div>
{% block body %}{% endblock %}

</body>
</html>

app/main/templates/main/cc_1.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>
        {{ content }}
    </h1>
{% endblock %}

app/main/templates/main/cc_2.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>
        {{ content }}
    </h1>
{% endblock %}

app/main/templates/main/dm.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>
        {{ content }}
    </h1>
{% endblock %}

app/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<div class="users">
    <h1>
        {{ content }}<br>
    </h1>
    <h1 style="color: red;">
        {{ company }}
    </h1>
    {% for pers in list_person%}

    <h1 class="test2">
        {{ pers.username }}<br>
    </h1>

    {% endfor %}
    {%if company == 'dm2'%}
    <h1>
        {%include "main/test.html"%}
    </h1>
    {% endif%}
</div>


{% endblock %}

app/main/templates/main/index_main.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Main</title>
  <link rel="stylesheet" href="{% static "deps/css/style_main.css" %}">

</head>
<body>
  <div class="container">

      <div class="logo">
        <a href="#"><img src="{% static "deps/img/logo 1.png" %}" alt="logo" title="Вы на главной странице"></a>
      </div>
      <div class="square1">
        <img src="{% static "deps/img/square1.png" %}" alt="square1">
        <a href="{% url "exam:exam" %}"><button title="Вход в раздел"><h3>Тестирование</h3></button></a>
      </div>
      <div class="square2">
        <img src="{% static "deps/img/square2.png" %}" alt="square2">
        <a href={% url "exam:CheckList" %}><button title="Вход в раздел"><h3>Чек-лист</h3></button></a>
      </div>
      <div class="personal">
        <img src="{% static "deps/img/personal.png" %}" alt="personal">
        <button id="open-modal" title="Войдите в раздел"><h3>Личный кабинет</h3></button>
      </div>
</div>
    <section class="main_content">
      <div class="block">
        <div class="datetime" id="datetime">
          <div class="date" id="date"></div>
          <div class="time" id="time"></div>
    </section>

  {% include "exam/index.html" %}
  <script>
      function updateClock() {
          const now = new Date();
          const days = ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'];
          const dayOfWeek = days[now.getDay()];
          const day = String(now.getDate()).padStart(2, '0');
          const month = String(now.getMonth() + 1).padStart(2, '0');
          const year = now.getFullYear();
          const hours = String(now.getHours()).padStart(2, '0');
          const minutes = String(now.getMinutes()).padStart(2, '0');
          const seconds = String(now.getSeconds()).padStart(2, '0');
          const dateString = `${dayOfWeek}, ${day}.${month}.${year}`;
          const timeString = `${hours}:${minutes}:${seconds}`;

          document.getElementById('date').textContent = dateString;
          document.getElementById('time').textContent = timeString;
      }

      setInterval(updateClock, 1000);
      updateClock();

      document.addEventListener('DOMContentLoaded', function() {
        var modal = document.getElementById('modal');
        var btn = document.getElementById('open-modal');
        var span = document.getElementsByClassName('close')[0];

        btn.onclick = function() {
          modal.style.display = 'block';
        }

        span.onclick = function() {
          modal.style.display = 'none';
        }

        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = 'none';
          }
        }
      });
  </script>
</body>
</html>

app/main/templates/main/test.html
<button> Тест, жмякай </button>