app/app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('users.urls', namespace='user')),
    path('exam/', include('exam.urls', namespace='exam')),


]

app/exam/urls.py
# from django.contrib import admin
from django.urls import path, include

from exam import views

app_name = 'exam'

urlpatterns = [
    path('', views.ExamView.as_view(), name='exam'),
    path('add/', views.AddInternView.as_view(), name='add_intern'),
    path('CheckList/', views.CheckListView.as_view(), name='CheckList'),
    path('edit/<int:pk>', views.ExamUpdateView.as_view(), name='edit_intern'),

]

app/exam/models.py
from django.db import models
from django import forms


class Exam(models.Model):
    call_center_list = [
        ("КЦ1", "КЦ1"),
        ("КЦ2", "КЦ2"),
        ("КЦ3", "КЦ3"),
    ]
    examiner_list = [
        ("Иванов", "Иванов"),
        ("Петров", "Петров"),
        ("Васечкин", "Васечкин"),
    ]
    result_list = [
        ("Не допущен", "Не допущен"),
        ("Допущен", "Допущен"),
        ("Неявка", "Неявка"),
        ("Отмена", "Отмена"),
        ("Не состоялось", "Не состоялось"),
    ]

    date_exam = models.DateField(blank=False, verbose_name="Дата зачета")
    name_intern = models.CharField(max_length=60, blank=False, verbose_name="Фамилия Имя стажера")
    cc = models.CharField(max_length=10, blank=False, choices=call_center_list, verbose_name="КЦ")
    time_exam = models.TimeField(blank=True, default="00:00", verbose_name="Время зачета")
    name_examiner = models.CharField(max_length=60, blank=True, verbose_name="ФИ сотрудника", choices=examiner_list)
    result_exam = models.CharField(max_length=25, blank=True, choices=result_list, default="",
                                   verbose_name="Результат")
    comment_exam = models.TextField(max_length=2000, blank=True, verbose_name="комментарий")

    def __str__(self):
        return f"{self.name_intern} {self.cc} {self.result_exam}"
        # return f"{self.username} {self.company}"

app/exam/forms.py
from django import forms
from .models import Exam


class AddInternForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ['date_exam', 'name_intern']

        widgets = {
            'date_exam': forms.DateInput(attrs={'type': 'date'})
        }


class EditInternForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ['date_exam', 'name_intern', 'time_exam', 'name_examiner', 'result_exam', 'comment_exam']
        widgets = {
            'date_exam': forms.DateInput(attrs={
                'type': 'date'}),
            'time_exam': forms.TimeInput(attrs={
                'type': 'time',
                'autofocus': 'autofocus'}),
            'name_examiner': forms.Select(attrs={
                'placeholder': 'Выбрать проверяющего',
                'class': 'test2'}),
            'result_exam': forms.Select(attrs={
                'class': 'test2'}),
            'comment_exam': forms.Textarea(attrs={
                'class': 'test2',
                'placeholder': 'Комментарий к зачету',
                'wrap': 'soft',
                'cols': 40,
            })
        }

app/exam/views.py
import datetime
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator

from django.views.generic import UpdateView, DetailView, TemplateView, FormView

from exam.forms import AddInternForm, EditInternForm
from exam.models import Exam


# @login_required
# def exam(request):
#     company = request.user.company
#     if company != "dm":
#         list_exam = Exam.objects.filter(cc=str(company))
#     else:
#         return render(request, 'exam/change_cc.html', {'title': 'Выбор КЦ', 'company': company})
#     context = {
#         'title': 'Зачеты',
#         'content': company,
#         'list_exam': list_exam,
#         'company': company,
#     }
#     # return render(request, 'exam/exam.html', context)
#     return render(request, 'exam/testing.html', context)
#
#
# @login_required
# def change_cc(request):
#     button_name = request.GET.get('btn')
#     list_exam = Exam.objects.filter(cc=str(button_name))
#     company = request.user.company
#     context = {
#         'title': button_name,
#         'content': button_name,
#         'list_exam': list_exam,
#         'company': company,
#     }
#     # return render(request, 'exam/exam.html', context)
#     return render(request, 'exam/testing.html', context)


# @login_required
# def exam_view(request):
#     # print(123)
#     # print(request.POST.get('exam_id', random.randint(100, 500)))
#     time = datetime.time(hour=0)
#     company = request.user.company
#     button_name = request.GET.get('btn', None)
#     form = AddInternForm()
#     if company == "dm" and not button_name:
#         return render(request, 'exam/change_cc.html', {'title': 'Выбор КЦ', 'company': company})
#
#     cc = button_name if company == "dm" else company
#     list_exam = Exam.objects.filter(cc=str(cc))
#     context = {
#         'title': button_name if button_name else 'Зачеты',
#         'content': cc,
#         'list_exam': list_exam,
#         'company': company,
#         'time': time,
#         'form': form,
#     }
#     return render(request, 'exam/testing.html', context)
#
#
# @login_required
# def add_intern(request):
#     if request.method == 'POST':
#         form = AddInternForm(request.POST)
#         if form.is_valid():
#             exam = form.save(commit=False)
#             exam.cc = request.user.company
#             form.save()
#             return redirect('exam:exam')
#
#     return render(request, 'exam/testing.html')


# @login_required
# def edit_intern(request, pk):
# print(123)
# print(request.POST.get('exam_id', random.randint(100, 500)))
# exam = get_object_or_404(Exam, pk=pk)

# if request.method == 'POST':
#     form = CcEditInternForm(request.POST, instance=exam)
# print(form)
# print(form.cleaned_data['name_intern'])
# print(form.cleaned_data['date_exam'])
# if form.is_valid():
# Exam.object.filter(id=pk).update(
#     name_intern=form.cleaned_data['name_intern'],
#     date_exam=form.cleaned_data['date_exam'])
# exam.date_exam = form.cleaned_data['date_exam']
# exam.name_intern = form.cleaned_data['name_intern']
# exam.save(update_fields=('date_exam', 'name_intern'))
# return redirect('exam:exam')
# else:
#     form = CcEditInternForm(instance=exam)
# return render(request, 'exam/testing.html', {'form': form})


# =====================================================================================================================


class ExamView(LoginRequiredMixin, TemplateView):
    template_name = 'exam/testing.html'

    def get(self, request, *args, **kwargs):
        company = request.user.company
        button_name = request.GET.get('btn', None)
        form = AddInternForm()

        if company == "dm" and not button_name:
            return render(request, 'exam/change_cc.html', {'title': 'Выбор КЦ', 'company': company})

        cc = button_name if company == "dm" else company
        list_exam = Exam.objects.filter(cc=str(cc))

        context = {
            'title': button_name if button_name else 'Зачеты',
            'content': cc,
            'list_exam': list_exam,
            'company': company,
            'time': datetime.time(hour=0),
            'form': form,
        }
        return self.render_to_response(context)


class AddInternView(LoginRequiredMixin, FormView):
    form_class = AddInternForm
    template_name = 'exam:exam'
    success_url = '/exam/'

    def form_valid(self, form):
        exam = form.save(commit=False)
        exam.cc = self.request.user.company
        print(exam.cc)
        exam.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


@method_decorator(login_required, name='dispatch')
class ExamUpdateView(UpdateView):
    model = Exam

    def dispatch(self, request, *args, **kwargs):
        self.user = request.user  # Получение пользователя и сохранение его как атрибут класса
        return super().dispatch(request, *args, **kwargs)

    def get_form_class(self):

        if self.user.company != 'dm':
            return AddInternForm
        else:
            return EditInternForm

    form_class = AddInternForm
    template_name = 'exam/update_intern.html'
    context_object_name = 'exam'

    def get_object(self, queryset=None):
        exam_id = self.kwargs.get('pk')
        return get_object_or_404(Exam, id=exam_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        exam = self.get_object()
        context['exam_date'] = exam.date_exam.strftime('%Y-%m-%d')
        context['list_exam'] = Exam.objects.filter(cc=exam.cc)
        context['cc'] = exam.cc
        return context

    def form_valid(self, form):
        exam = form.save(commit=False)
        exam.save()
        return redirect("exam:exam")


class CheckListView(LoginRequiredMixin, TemplateView):
    template_name = 'exam/checklist.html'
    context_object_name = 'exam'

app/exam/templates/exam/change_cc.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}

<div class="users button_style">
    <button class="sendDataButton" data-value="КЦ1">КЦ1</button>
    <button class="sendDataButton" data-value="КЦ2">КЦ2</button>
    <button class="sendDataButton" data-value="КЦ3">КЦ3</button>
    <script>
        document.querySelectorAll('.sendDataButton').forEach(function(button) {
            button.addEventListener('click', function() {
                var dataValue = this.getAttribute('data-value');
                window.location.href = '/exam/?btn=' + encodeURIComponent(dataValue);
            });
        });
    </script>
</div>


{% endblock %}

app/exam/templates/exam/checklist.html
{% extends "main/index_main.html" %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}






{% endblock %}

app/exam/templates/exam/exam.html
{% extends "main/base.html" %}
{% load static %}
{% load custom_filters %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<div class="users">
    <h1>
        {{ content }}
    </h1>
</div>
<div class="table">
    <table>
        <thead>
        <tr>
            <th>Дата</th>
            <th>ФИО оператора</th>
            <th>Время (МСК)</th>
            <th>ФИ специалиста</th>
            <th>Результат ТЗ</th>
            <th>Комментарий</th>
        </tr>
        </thead>
        <tbody>
        {% for elem in list_exam %}
        <tr>
            <td> {{ elem.date_exam }}</td>
            <td> {{ elem.name_intern }}</td>
            <td> {{ elem.time_exam }} - {{ elem.time_exam|add_minutes:30 }}</td>
            <td> {{ elem.name_examiner }}</td>
            <td> {{ elem.result_exam }}</td>
            <td> {{ elem.comment_exam }} </td>
            <td class="link" data-row={{ elem.id }} ><a href="#">Персонаж с id {{ elem.id}}</a></td>
<!--            <td> <button class="sendDataButton" data-value="Редактировать">{{ elem.id}}</button> </td>-->
        </tr>
        {% endfor %}

        <!-- Добавьте больше строк по необходимости -->
        </tbody>
    </table>

{% endblock %}

app/exam/templates/exam/index.html
<!--<!DOCTYPE html>-->
<!--<html lang="ru">-->
<!--<head>-->
<!--  <meta charset="UTF-8">-->
<!--  <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--  <title>Document</title>-->
<!--  <link rel="stylesheet" href="./style.css">-->
<!--</head>-->
{% load static %}

<link rel="stylesheet" href="{% static "deps/css/main.css" %}">


  <h1 style="display: none;">Дневная выработка, планируется на главной странице приложения</h1>
  <div class="main">
    <table>
      <thead>
        <tr>
          <th>Работа за день</th>
          <th>Звонки</th>
          <th>Письма</th>
          <th>ТЗ</th>
          <th>Выработка</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>Субботина Крис</th>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>0,00%</td>
        </tr>
        <tr>
          <th>Дорофеева Алия</th>
          <td>10</td>
          <td>10</td>
          <td>10</td>
          <td>0,00%</td>
        </tr>
        <tr>
          <th>Моисеева Кара</th>
          <td>10</td>
          <td>10</td>
          <td>10</td>
          <td>0,00%</td>
        </tr>
        <tr>
          <th>Шарапова Инга</th>
          <td>10</td>
          <td>10</td>
          <td>10</td>
          <td>0,00%</td>
        </tr>
        <tr>
          <th>Доронин Гордей</th>
          <td>10</td>
          <td>10</td>
          <td>10</td>
          <td>0,00%</td>
        </tr>
      </tbody>
    </table>
  </div>

app/exam/templates/exam/testing.html
{% extends "main/base.html" %}
{% load static %}
{% load custom_filters %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static "deps/css/style_testing.css" %}">
<div class="header container">
    <div class="logo">
        <a href="#" title="На главную страницу">
            <img src="{% static "deps/img/logo 1.png" %}" alt="logo">
        </a>
    </div>
    <div class="navigation">
        <div class="nav-item">
            <img src="{% static "deps/img/square1.png" %}" alt="square1">
            <a href="#">
                <button title="Вы находитесь в этом разделе"><h3>Тестирование</h3></button>
            </a>
        </div>
        <div class="nav-item">
            <img src="{% static "deps/img/personal.png" %}" alt="personal">
            <a href="#">
                <button title="Самый лучший сотрудник!"><h3>Личный кабинет</h3></button>
            </a>
        </div>
    </div>
</div>

<div class="table container">
    <div class="table-header">
        <table class="block">
            <thead>
            <tr>
                <th class="date-column">
                    <div>Дата</div>
                </th>
                <th>
                    <div>ФИО оператора</div>
                </th>
                <!--            <th><div>Форма обучения</div></th>-->
                <!--            <th><div>Попытка</div></th>-->
                <th>
                    <div>Время (МСК)</div>
                </th>
                <th>
                    <div>ФИ специалиста</div>
                </th>
                <th>
                    <div>Результат ТЗ</div>
                </th>
                <th>
                    <div>Комментарий</div>
                </th>
                <!--            <th><div>ФИ обучающего/обучающих</div></th>-->
                <!--            <th><div>ФИ принимающего внутреннее ТЗ</div></th>-->
                <th>
                    <div>Действия</div>
                </th>
            </tr>
            </thead>
            <tbody id="table-body">
            {% for elem in list_exam %}
            <tr>
                <td> {{ elem.date_exam }}</td>
                <td> {{ elem.name_intern }}</td>
                <td>
                    {% if elem.time_exam.hour == time.hour %}

                    {% else %}
                    {{ elem.time_exam }} - {{ elem.time_exam|add_minutes:30 }}
                    {% endif %}
                </td>
                <td> {{ elem.name_examiner }}</td>
                <td> {{ elem.result_exam }}</td>
                <td> {{ elem.comment_exam }}</td>
                <td>

                        <a href="{% url "exam:edit_intern" elem.id %}">
                            <button type="submit">
                                Редактировать стажера с id {{ elem.id }}
                            </button>
                        </a>

                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>



{% block add %}{% endblock %}

{% if company != "dm"%}
    <div class="main container">
      <div class="new-row-container">
              <button formmethod="get" id="modal-open-btn" class="new_row" title="Добавить">
                  <img src="{% static "deps/img/icons8_plus.svg" %}" alt="plus icon">
              </button>
      </div>
    </div>

    <!--    Модалка для добавления данных   -->

    <div id="modal" class="modal">
        <div class="modal-content">
          <span class="close-btn">&times;</span>
          <h2>Добавить стажёра</h2>
          <form method="post" id="add-student-form" action="{% url "exam:add_intern" %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit" id="save-btn">Сохранить</button>
          </form>
        </div>
      </div>

        <!--    Конец блока добавления данных   -->



{% endif %}

    <script src="{% static "deps/js/script_testing.js" %}"></script>


<script>



          function openEditModal(id) {
            document.getElementById('modal-edit').style.display = 'block';
            }


  </script>

</body>
</html>

{% endblock %}

app/exam/templates/exam/update_intern.html
{% extends "exam/testing.html" %}
{% load static %}

{% block add %}
<link rel="stylesheet" href="{% static "deps/css/add_intern.css" %}">

    <div class="add_intern add_modal">
        <span>
            <a class="close-btn" href="{% url "exam:exam" %}">
                &times;
            </a>
        </span>
        <h2>Редактировать</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Сохранить</button>
        </form>
    </div>


<script>
    document.addEventListener('DOMContentLoaded', function() {
        var dateInput = document.querySelector('input[type="date"]');
        if (dateInput) {
            dateInput.value = "{{ exam_date }}";
        }
    });
</script>

{% endblock %}